Added support for custom shell installer

diff --git a/linux/archive.install b/linux/archive.install
--- a/linux/archive.install
+++ b/linux/archive.install
@@ -1,7 +1,9 @@
+
+
+
+
 post_install() {
-    log() {
-        echo "$@" 
-    }
+    
     #
     # Prepares systemd support by creating a symlink for the .service file
     # and enabling/disabling certain features of our .service unit based on
@@ -26,7 +28,7 @@ post_install() {
                 systemctl daemon-reload ||:
             fi
 
-            log "Configuring portmaster.service to launch at boot"
+            log "info" "Configuring portmaster.service to launch at boot"
             systemctl enable portmaster.service ||:
         fi
     }
@@ -47,8 +49,12 @@ post_install() {
     #
     # Fix selinux permissions for portmaster-start
     #
-    if command -V getenforce >/dev/null 2>&1; then
-        chcon -t bin_t /opt/safing/portmaster/portmaster-start
+    if command -V chcon >/dev/null 2>&1; then
+        # chcon -t bin_t -u system_u /opt/safing/portmaster/portmaster-start || :
+    fi
+    if command -V semanage >/dev/null 2>&1; then
+        # semanage fcontext -m -t bin_t -s system_u /opt/safing/portmaster/portmaster-start || :
+        # restorecon -v /opt/safing/portmaster/portmaster-start || :
     fi
 
     #
@@ -61,21 +67,19 @@ post_install() {
     # it is more likely to fail and is thus the last thing we do.
     #
     if [ "${skip_downloads}" = "True" ]; then
-        log "Downloading of Portmaster modules skipped!"
-        log "Please run '/opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster update' manually.\n"
+        log "info" "Downloading of Portmaster modules skipped!"
+        log "info" "Please run '/opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster update' manually.\n"
         return
     fi
     log "Downloading portmaster modules. This may take a while ..."
     /opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster update --update-agent "${download_agent}" 2>/dev/null >/dev/null || (
-        log "Failed to download modules"
-        log "Please run '/opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster update' manually.\n"
+        log "error" "Failed to download modules"
+        log "error" "Please run '/opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster update' manually.\n"
     )
 }
 
 post_upgrade() {
-    log() {
-        echo "$@" 
-    }
+    
     #
     # Prepares systemd support by creating a symlink for the .service file
     # and enabling/disabling certain features of our .service unit based on
@@ -100,7 +104,7 @@ post_upgrade() {
                 systemctl daemon-reload ||:
             fi
 
-            log "Configuring portmaster.service to launch at boot"
+            log "info" "Configuring portmaster.service to launch at boot"
             systemctl enable portmaster.service ||:
         fi
     }
@@ -120,37 +124,33 @@ post_upgrade() {
     #
     if [ -d /var/lib/portmaster ]; then
         if [ ! -d /opt/safing/portmaster/config.json ]; then
-            log "Migrating from previous installation at /var/lib/portmaster to /opt/safing/portmaster ..."
+            log "info" "Migrating from previous installation at /var/lib/portmaster to /opt/safing/portmaster ..."
             mv /var/lib/portmaster/databases /opt/safing/portmaster/databases ||:
             mv /var/lib/portmaster/config.json /opt/safing/portmaster/config.json ||:
         fi
-        log "Removing previous installation directory at /var/lib/portmaster"
+        log "info" "Removing previous installation directory at /var/lib/portmaster"
         rm -r /var/lib/portmaster 2>/dev/null >&2 ||:
     fi
 
 }
 
 pre_remove() {
-    log() {
-        echo "$@" 
-    }
+    
     # stop the portmaster service and disable it if it's enabled.
     if command -V systemctl >/dev/null 2>&1; then
         if (systemctl -q is-active portmaster.service); then
-            log "Stopping portmaster.service"
+            log "info" "Stopping portmaster.service"
             systemctl stop portmaster.service ||:
         fi
         if (systemctl -q is-enabled portmaster.service); then
-            log "Disabling portmaster.service to launch at boot"
+            log "info" "Disabling portmaster.service to launch at boot"
             systemctl disable portmaster.service ||:
         fi
     fi
 }
 
 post_remove() {
-    log() {
-        echo "$@" 
-    }
+    
     rm -rf /opt/safing/portmaster/updates ||:
 
     # file is marked as a ghost on RPM system so it might have
